### ISSUE TITLE
vpr_autoid_create - export new autoid files with .txt extension?

### ISSUE THREAD

**Issue by kevinsorochan** [EOGrady21/vprr#69]
**Describe the bug**
This is more of a feature request, but it would be preferable to have a file extension on the new autoid files generated from vpr_autoid_create

**Comment by EOGrady21** [comment]
This is an artefact of VP and changing it would I think significantly impact reverse compatibility. Is there a significant benefit to adding a .txt file extension? It is more generic but may actually lead to confusion since they are not really just any txt file, they have a specific format/ structure which needs to be adhered to in order for the rest of the package functions to work.

**Comment by kevinsorochan** [comment]
Also - from the vignette:

The data inputs for processing in vprr consist of the following file types: aid (.txt), aidmeas (.txt), and CTD (.dat).

**Comment by EOGrady21** [comment]
changes implemented in  commit 1b24042e45d46900eef74b4ac08adb34f906e5e6

@kevinsorochan please test and close if the issue is resolved

**Comment by kevinsorochan** [comment]
new files are still generated without .txt extension

**Comment by EOGrady21** [comment]
Thanks Kevin, I have updated this again hopefully in the right spot.

**Comment by kevinsorochan** [comment]
Text files are now exported
